apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: opc-ecosystem-images
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/opc-ecosystem-images@sha256:97ba3f5cb6d20609de1133ea6e176884f103222b59fa8155190d3b95e7f5f43a
        name: container-image
        resources: {}
status: {}
